language: csharp
mono: none
dotnet: 9.0.306

install:
  - dotnet restore "HotelBooking.Mvc/HotelBooking.Mvc.csproj"
  - dotnet restore "HotelBooking.WebApi/HotelBooking.WebApi.csproj"
  - npm install -g newman

script:
  # Build and run unit tests
  - dotnet build "HotelBooking.Mvc/HotelBooking.Mvc.csproj" --configuration Release
  - dotnet build "HotelBooking.WebApi/HotelBooking.WebApi.csproj" --configuration Release
  - dotnet test "HotelBooking.UnitTests/HotelBooking.UnitTests.csproj" --no-build --configuration Release --logger:trx

  # Start the API in the background
  - dotnet run --project "HotelBooking.WebApi/HotelBooking.WebApi.csproj" --no-build &
  - sleep 10

  # Run Postman tests
  - newman run "Postman/HotelBooking.postman_collection.json" --insecure
