language: node_js
node_js:
  - "22"

install:
  - npm install -g newman
    
before_script:
  - export ASPNETCORE_URLS="https://+:5001;http://+:5000"
  - dotnet restore Week\ 39\ -\ Mini\ Project/HotelBooking_Clean_Async/HotelBooking.API/HotelBooking.API.csproj
  - dotnet build Week\ 39\ -\ Mini\ Project/HotelBooking_Clean_Async/HotelBooking.API/HotelBooking.API.csproj
  - dotnet run --project Week\ 39\ -\ Mini\ Project/HotelBooking_Clean_Async/HotelBooking.API/HotelBooking.API.csproj &
  - sleep 10

script:
  - newman run 'Week 39 - Mini Project/HotelBooking_Clean_Async/Postman/HotelBooking.postman_collection.json' --insecure
